[Log]
Level = 'warn'

[WebServer]
AllowOrigins = '*'
SecureCookies = false

[WebServer.TLS]
HTTPSPort = 0

[[EVM]]
ChainID = '5'
LinkContractAddress = '0x326C977E6efc84E512bB9C30f76E30c160eD06FB'
MinContractPayment = '0.000000001 link'

[[EVM.Nodes]]
Name = 'Goerli'
WSURL = 'wss://eth-goerli.g.alchemy.com/v2/sgcBjikzerJibFP56D_ohhvTV54WChaZ'
HTTPURL = 'https://eth-goerli.g.alchemy.com/v2/sgcBjikzerJibFP56D_ohhvTV54WChaZ'

